# Generated by Django 2.2 on 2019-04-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='文章图片'),
        ),
    ]
