# Generated by Django 3.0.1 on 2019-12-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.IntegerField(verbose_name='日志类型')),
                ('log_content', models.CharField(max_length=100, verbose_name='日志内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='手机号')),
                ('open_id', models.CharField(max_length=40, unique=True, verbose_name='微信号')),
                ('img', models.CharField(default='img_null', max_length=100, verbose_name='微信头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False, verbose_name='设备标识')),
                ('serial_num', models.CharField(max_length=40, unique=True, verbose_name='序列号')),
                ('name', models.CharField(max_length=40, verbose_name='设备名')),
                ('remark', models.CharField(max_length=50, verbose_name='设备备注')),
                ('access_ctrl', models.BooleanField(verbose_name='访问控制启用')),
                ('c_pass', models.CharField(default='123456', max_length=20, verbose_name='控制密码')),
                ('position', models.IntegerField(default=0, verbose_name='设备开度')),
                ('io_state', models.IntegerField(default=0, verbose_name='阀门开关量控制')),
                ('accuracy', models.IntegerField(default=0, verbose_name='调节精度')),
                ('state', models.IntegerField(default=0, verbose_name='阀门状态')),
                ('network', models.IntegerField(default=0, verbose_name='网路连接')),
                ('error', models.IntegerField(default=0, verbose_name='故障信息')),
                ('adm_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.User', verbose_name='管理员账户')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.DeviceLog', verbose_name='系统日志')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_name', models.CharField(max_length=40, verbose_name='设备备注')),
                ('source', models.IntegerField(verbose_name='权限来源')),
                ('a_access', models.IntegerField(default=0, verbose_name='a_access')),
                ('p_access', models.IntegerField(default=0, verbose_name='p_access')),
                ('a_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='授权用户手机号', to='blog.User', verbose_name='授权用户手机号')),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Device', verbose_name='设备标识')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='用户手机', to='blog.User', verbose_name='用户手机号')),
            ],
            options={
                'verbose_name': '推荐位',
                'verbose_name_plural': '推荐位',
                'unique_together': {('phone', 'device_id')},
            },
        ),
    ]
