# Generated by Django 3.0 on 2019-12-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceId', models.AutoField(primary_key=True, serialize=False, verbose_name='设备标识')),
                ('serialNum', models.CharField(max_length=40, unique=True, verbose_name='序列号')),
                ('name', models.CharField(max_length=40, verbose_name='设备名')),
                ('remark', models.CharField(max_length=50, verbose_name='设备备注')),
                ('accessCtrl', models.BooleanField(verbose_name='访问控制启用')),
                ('cPass', models.CharField(default='123456', max_length=20, verbose_name='控制密码')),
                ('position', models.IntegerField(default=0, verbose_name='设备开度')),
                ('ioState', models.IntegerField(default=0, verbose_name='阀门开关量控制')),
                ('accuracy', models.IntegerField(default=0, verbose_name='调节精度')),
                ('state', models.IntegerField(default=0, verbose_name='阀门状态')),
                ('network', models.IntegerField(default=0, verbose_name='网路连接')),
                ('error', models.IntegerField(default=0, verbose_name='故障信息')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='手机号')),
                ('openId', models.CharField(max_length=40, unique=True, verbose_name='微信号')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logType', models.IntegerField(verbose_name='日志类型')),
                ('logContent', models.CharField(max_length=100, verbose_name='日志内容')),
                ('logTime', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
                ('deviceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Device', verbose_name='设备标识')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='adminPhone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.User', verbose_name='管理员账户'),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarkName', models.CharField(max_length=40, verbose_name='设备备注')),
                ('source', models.IntegerField(verbose_name='权限来源')),
                ('aAccess', models.IntegerField(default=0, verbose_name='aAccess')),
                ('pAccess', models.IntegerField(default=0, verbose_name='pAccess')),
                ('aPhone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='授权用户手机号', to='blog.User', verbose_name='授权用户手机号')),
                ('deviceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Device', verbose_name='设备标识')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='用户手机', to='blog.User', verbose_name='用户手机号')),
            ],
            options={
                'verbose_name': '推荐位',
                'verbose_name_plural': '推荐位',
                'unique_together': {('phone', 'deviceId')},
            },
        ),
    ]
