# Generated by Django 2.2 on 2019-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190421_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='文章图片'),
        ),
    ]
