# Generated by Django 2.2.1 on 2019-05-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190517_2046'),
        ('blog', '0004_auto_20190517_2128'),
    ]

    operations = [
    ]
